# Generated by Django 4.2.7 on 2024-02-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('density', models.IntegerField(verbose_name='Densidad')),
                ('young_module', models.FloatField(verbose_name='Módulo de Young')),
                ('loss_factor', models.FloatField(verbose_name='Factor de perdidas')),
                ('poisson_module', models.FloatField(verbose_name='Módulo de Poisson')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_acoustic_iso.materials')),
            ],
        ),
    ]
