# Generated by Django 4.2.7 on 2024-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='title')),
                ('section', models.CharField(max_length=15, verbose_name='section')),
                ('pub_date', models.DateField(db_comment='Date and time when the article was published')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
