# Generated by Django 4.2.7 on 2024-03-05 05:45

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('D:/media/uploads/projects'), verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateField(db_comment='Date and time when the article was published', verbose_name='Publication Date'),
        ),
    ]
