# Generated by Django 4.2.7 on 2024-03-05 07:18

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('D:/Programacion/portfolio/media/uploads/projects'), verbose_name='Cover Image'),
        ),
    ]
